---
- name: Check for fluent-bit service
  stat:
    path: /apps_ux/s6_services/fluent-bit/run
  register: fluent_bit_run
  become: yes
  become_user: wwwadm
  tags:
  - delete-app

- name: Stop fluent-bit
  include_role:
    name: tomcat_stop
    apply:
      tags: [delete-app]
  when: fluent_bit_run.stat.exists
  tags:
  - delete-app

- name: Create deploy conf directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - '{{ apm_agent_home }}/conf/deploy'
    - '{{ apm_agent_home }}/conf/deploy/input'
    - '{{ apm_agent_home }}/conf/deploy/parser'
  become: yes
  become_user: wwwadm

- name: Configuration files
  template:
    src: '{{ item }}'
    dest: '{{ apm_agent_home }}/conf/deploy/{{ item }}'
    mode: '0664'
  loop:
    - input/inputs.conf
    - parser/parsers.conf
  become: yes
  become_user: wwwadm

- name: Remove component config
  file:
    state: absent
    path: '{{ apm_agent_home }}/conf/deploy'
  become: yes
  become_user: wwwadm
  tags:
  - never
  - delete-app

- name: Start fluent-bit
  include_role:
    name: tomcat_start
    apply:
      tags: delete-app
  when: fluent_bit_run.stat.exists
  tags:
  - molecule-notest
  - delete-app
