---
- name: Create /sw_ux/bin directory
  file:
    path: '/sw_ux/bin'
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ install_user }}"

- name: Download Hashicorp Vault
  environment: '{{ proxy_env | default({}) }}'
  get_url:
    url: 'https://releases.hashicorp.com/vault/1.7.1/vault_1.7.1_linux_amd64.zip'
    dest: '/tmp/vault_1.7.1_linux_amd64.zip'
    checksum: 'sha256:https://releases.hashicorp.com/vault/1.7.1/vault_1.7.1_SHA256SUMS'
    mode: '0644'
  become: yes
  become_user: "{{ install_user }}"

- name: Extract Hashicorp Vault
  unarchive:
    src: '/tmp/vault_1.7.1_linux_amd64.zip'
    dest: '/sw_ux/bin'
    remote_src: yes
    mode: '755'
  become: yes
  become_user: "{{ install_user }}"
  when: not ansible_check_mode