---
- name: Check for fluent-bit service
  stat:
    path: /apps_ux/s6_services/fluent-bit/run
  register: fluent_bit_run
  become: yes
  become_user: "{{ install_user }}"
  tags:
  - uninstall

- name: Stop fluent-bit
  include_role:
    name: tomcat_stop
    apply:
      tags: uninstall
  when: fluent_bit_run.stat.exists
  tags:
  - uninstall

- name: Create metrics conf directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - '{{ apm_agent_home }}/conf/metrics'
    - '{{ apm_agent_home }}/conf/metrics/filter'
    - '{{ apm_agent_home }}/conf/metrics/input'
    - '{{ apm_agent_home }}/conf/metrics/parser'
  become: yes
  become_user: "{{ install_user }}"

- name: Configuration files
  copy:
    src: 'conf'
    dest: '{{ apm_agent_home }}'
    mode: '0644'
  become: yes
  become_user: "{{ install_user }}"

- name: Create metrics scripts directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - '{{ apm_agent_home }}/scripts/metrics'
  become: yes
  become_user: "{{ install_user }}"

- name: Script files
  copy:
    src: 'scripts'
    dest: '{{ apm_agent_home }}'
    mode: '0755'
  become: yes
  become_user: "{{ install_user }}"

- name: Remove metrics config
  file:
    state: absent
    path: '{{ apm_agent_home }}/conf/metrics'
  become: yes
  become_user: "{{ install_user }}"
  tags:
  - never
  - uninstall

- name: Remove metrics scripts
  file:
    state: absent
    path: '{{ apm_agent_home }}/scripts/metrics'
  become: yes
  become_user: "{{ install_user }}"
  tags:
  - never
  - uninstall

- name: Start fluent-bit
  include_role:
    name: tomcat_start
    apply:
      tags: uninstall
  tags:
  - molecule-notest
  - uninstall