---
- name: Check for logrotate
  ansible.builtin.command: which logrotate
  register: logrotate

- name: logrotate configuration file
  template:
    src: 'templates/conf/logrotate.conf'
    dest: '/apps_ux/wwwsvr/logrotate.conf'
    mode: '0664'
  become: yes
  become_user: wwwsvr
  when: logrotate.rc == 0

- name: crontab for logrotate
  ansible.builtin.cron:
    name: "Logrotate for Fluent Bit"
    minute: "59"
    hour: "11"
    user: wwwsvr
    job: "/sbin/logrotate /apps_ux/wwwsvr/logrotate.conf --state /apps_ux/wwwsvr/logrotate-state --verbose"
  become: yes
  become_user: wwwsvr
  when: logrotate.rc == 0