---
- name: Check for vault broker token
  assert:
    that:
      - vault_broker_token | default('') | length > 0 
    msg: 'Vault broker token variable must not be empty'
  tags:
  - molecule-notest

- name: Create app directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0775'
  loop:
    - '{{ apm_agent_home }}'
    - '{{ apm_agent_home }}/bin'
    - '{{ apm_agent_home }}/conf'
  become: yes
  become_user: wwwadm

- name: envconsul configuration file
  template:
    src: 'templates/{{ item }}'
    dest: '{{ apm_agent_home }}/{{ item }}'
    mode: '0664'
  become: yes
  become_user: wwwadm
  loop:
    - conf/fluent-bit.hcl
    
- name: Add run file
  import_tasks: add-env-file.yml
