---
- name: Create /sw_ux/bin directory
  file:
    path: '/sw_ux/bin'
    state: directory
    mode: '0755'
  become: yes
  become_user: wwwadm

- name: Download Hashicorp Consul Template
  environment: '{{ proxy_env }}'
  get_url:
    url: 'https://releases.hashicorp.com/consul-template/0.27.1/consul-template_0.27.1_linux_amd64.zip'
    dest: '/tmp/consul-template_0.27.1_linux_amd64.zip'
    checksum: 'sha256:https://releases.hashicorp.com/consul-template/0.27.1/consul-template_0.27.1_SHA256SUMS'
    mode: '0644'
    use_proxy: yes
  become: yes
  become_user: wwwadm

- name: Extract Hashicorp Consul Template
  unarchive:
    src: '/tmp/consul-template_0.27.1_linux_amd64.zip'
    dest: '/sw_ux/bin'
    remote_src: yes
    mode: '0755'
  become: yes
  become_user: wwwadm
  when: not ansible_check_mode