---
# roles/jdk/tasks/main.yml

- debug:
    msg: '{{ ansible_os_family }} {{ ansible_architecture }} {{ jdk_version }} {{ jdk_type }}'

- name: 'Include parameters for {{ ansible_os_family }} {{ ansible_architecture }} JDK:{{ jdk_version }} type:{{ jdk_type }}'
  include_vars:
    file: "{{ ansible_os_family }}_{{ ansible_architecture }}_jdk{{ jdk_version }}_{{ jdk_type }}.yml"

- name: directory "{{ jdk_home }}"
  file:
    path: "{{ jdk_home }}"
    state: directory
    mode: 0755
  become:  yes
  become_user: "{{ jdk_install_as }}"

- name: Show JDK package info
  debug:
    var: jdk_archive

- name: Download JDK archive
  get_url:
    url: "{{ jdk_archive.url }}"
    url_username: "{{ artifactory_username | default('') }}"
    url_password: "{{ artifactory_password | default('') }}"
    dest: "/tmp/{{ jdk_archive.filename }}"
    checksum: "{{ jdk_archive.checksum }}"
    validate_certs: false
    timeout: 1000
  become: yes
  become_user: "{{ jdk_install_as }}"

- name: 'Extract JDK archive'
  unarchive:
    src: "/tmp/{{ jdk_archive.filename }}"
    dest: "{{ jdk_install_root }}"
    extra_opts: ['--transform=s,/*[^/]*,{{ jdk_install_dir | basename }},i', '--show-stored-names']
    remote_src: yes
  become: yes
  become_user: "{{ jdk_install_as }}"