---
- name: Create /sw_ux/bin directory
  file:
    path: '/sw_ux/bin'
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ install_user }}"

- name: Download jq
  environment: '{{ proxy_env | default({}) }}'
  get_url:
    url: 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64'
    dest: '/sw_ux/bin/jq'
    mode: '755'
  become: yes
  become_user: "{{ install_user }}"  
  when: not ansible_check_mode